### ISSUE TITLE
Renaming weekly to newsletters maybe?

### ISSUE THREAD

**Issue by itsN1X** [NixOS/nixos-weekly#25]
Hey @garbas , I was wondering if I could help in restructuring the nix public outreach regimes.
I could contribute in documentation, nix-artwork and the weekly, to make nix more presentable aesthetically. I'd love if you add me to the @nixOS org so that i could start off right away. I could also help with tagging and easing the issue workflows.
Tysm in advance, and happy new year's.

**Comment by garbas** [comment]
@itsN1X hpny! that would be awesome.

i will release first nixos weekly today, since it is start of the year. and we can already start preparing and improving next one. design and content wise. gradual improvement so by the end of the year we should have a proper channel for nixos/nix news :)

if you want to help with the first one, just ping me on irc (garbas @ freenode).

**Comment by itsN1X** [comment]
:D 
I'd love to get involved!
