### ISSUE TITLE
a script to figure out new git contributors

### ISSUE THREAD

**Issue by garbas** [NixOS/nixos-weekly#5]
for each project nix / nixpkgs

what is a new contributor? contributors that appear since last blog release

**Comment by garbas** [comment]
this is what we currently have 

```
#!/bin/env bash
set -x
WEEKS=${WEEKS:-1}
timestamp=$(echo "$(date +%s) - ($WEEKS * 604800)" | bc)
git log --date=raw --pretty="%an %ae,%at" \
  | sort | awk -F "," '!a[$1]++' \
  | awk -v weekago="$timestamp" -F "," '$2 >= weekago { print $1 }'
```

**Comment by vcunat** [comment]
There are also public links already providing such info, e.g. https://www.openhub.net/p/nixos/contributors?sort=newest though this one might not update often enough to be in "weekly" posts.

**Comment by 7c6f434c** [comment]
> There are also public links already providing such info, e.g. https://www.openhub.net/p/nixos/contributors?sort=newest though this one might not update often enough to be in "weekly" posts.

I guess this can be useful for finding the very newest contributors.

But it «splits» more or less every person where there is a risk of
split.

**Comment by vcunat** [comment]
@7c6f434c: maybe it will be easiest to run the `<nixpkgs/maintainers/scripts/vanity.sh>` script twice and diff the output somehow? (or something similar)

**Comment by 7c6f434c** [comment]
> @7c6f434c: maybe it will be easiest to run the `<nixpkgs/maintainers/scripts/vanity.sh>` script twice and diff the output somehow? (or something similar)

That would work, although there are some more github-name-retrieval
corner cases that may merit some fixes.

But running it w.r.t. different current versions, optionally applying 
a threshold then diffing the list of people should work fine. vanity.sh
is not fully optimised for this because the representative name can
change when a better name becomes available, so some minimal care has to
be applied.

Maybe I was wrong in not including the first commit by a person in the
output… That should be fine (we can get fewer committers next time if we
find out some two aliases are the same person, but not more).

**Comment by aljones15** [comment]
what about using the github api?

https://developer.github.com/v3/projects/collaborators/#list-collaborators

just store the list of collabs from last week and then each Saturday night get a new list and see new collaborators. I did a relay graphql project using this so could build a pretty simple app that does this if you want. although I guess contributors would require a different api endpoint.

**Comment by domenkozar** [comment]
I'm going to close this one. I don't see much benefit in adding those users in a weekly. I do believe each contributor is very welcome and I'd prefer to thank each one, but realistically I don't see how anyone would like to read that each week.

Maybe it should instead be part of Nix project releases?

**Comment by peterhoeg** [comment]
> Maybe it should instead be part of Nix project releases?

 Great idea.
